name: Docker run test
on:
    push:
        branches: ["main"]

jobs:
    DOCKER:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

         # Set up DOcker Buildx
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
          
        # Build and push Docker Image
        - name: Build and Push Docker Image
          uses: docker/build-push-action@v6
          with:
            context: . # Build context (current directory)
            file: ./Dockerfile #path to Dockerfile (if it's in the root of the repository)
            push: true # Push the image after building
            tags: ${{ secrets.DOCKER_USERNAME}}/my-app:latest # Tag the image
